challenge/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "employees#index"

  resources :employees do
    get 'result', on: :collection, defaults: { format: :csv }
  end
end

challenge/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

challenge/app/models/benefit.rb
class Benefit < ApplicationRecord
  belongs_to :employee

  # months - class method to get months of benefits
  # iterate over min and max month founded in the table
  # @return array with months min to max
  def self.months
    min = all.minimum(:month)
    max = all.maximum(:month)
    months = []

    while min <= max
      months << min
      min += 1.month
    end
    months
  end
end

challenge/app/models/concerns/generate_csv.rb
module GenerateCsv
  extend ActiveSupport::Concern

  class_methods do
    # to_csv - class method return csv data file,
    # @return csv file, call build_data_to_csv method to get headers and rows to file
    def to_csv
      data = build_data_to_csv
      CSV.generate(headers: true) do |csv|
        csv << (data[:headers])
        data[:rows].each do |row|
          csv << row
        end
      end
    end

    private

    # build_data_to_csv - class method return csv data file, overwrite this method in every class
    # to return the corresponding data
    # @return hash with headers and rows
    def build_data_to_csv
      { headers: [],
        rows: [[]] }
    end
  end
end

challenge/app/models/employee.rb
class Employee < ApplicationRecord
  include ::GenerateCsv
  belongs_to :employee_invite
  has_many :benefits

  # total_benefit - calculate total benefit of employee
  # @return sum of amount benefits
  def total_benefit
    benefits.sum(:amount)
  end

  class << self
    private

    # build_data_to_csv - overwrite module method, build headers and rows to csv file,
    # add attributes of employee, and call months method of Benefit class for retrieve all
    # possible months that exist in the table
    # @return hash with headers and rows
    def build_data_to_csv
      attributes = ["name", "email", "start_date", "total_benefit"]
      months = Benefit.months
      { headers: build_header(attributes, months),
        rows: build_rows(attributes, months) }
    end

    # build_header - build headers to csv file
    # @attributes - array of attributes of an employee
    # @months - array of months of benefits
    # @return array with headers to csv file, attributes and months with Month-Year format
    def build_header(attributes, months)
      attributes.map { |a| a.gsub('_', ' ').capitalize } + months.map { |m| m.strftime("%B-%Y") }
    end

    # build_rows - build rows to csv file
    # @attributes - array of attributes of an employee
    # @months - array of months of benefits
    # @return array with rows to csv file, get the attributes for every employee,
    # get average amount of benefits grouped by month for employee,
    # create new array and match data with the month of the header, if match puts data else puts empty string,
    # finally merge in one array
    def build_rows(attributes, months)
      rows = []
      all.each do |employee|
        attr_arr = attributes.map{ |attr| employee.send(attr) }
        benefits = employee.benefits.group(:month).average(:amount)
        benefits_array = []
        months.each do |month|
          benefits_array << benefits[month] || ' '
        end
        attr_arr += benefits_array
        rows << attr_arr
      end
      rows
    end

  end
end

challenge/app/models/employee_invite.rb
class EmployeeInvite < ApplicationRecord
  has_one :employee
end

challenge/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

challenge/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end

  def result
    respond_to do |format|
      format.csv { send_data Employee.to_csv, filename: "employees_#{Time.now}.csv", status: :ok }
    end
  end
end

challenge/app/helpers/application_helper.rb
module ApplicationHelper
end

challenge/app/helpers/employees_helper.rb
module EmployeesHelper
end

challenge/app/views/employees/index.html.erb
<div>
  <div class="flex justify-end mb-2">
    <%= link_to  "Get Report", result_employees_path, class:"inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
  </div>
  <!-- This example requires Tailwind CSS v2.0+ -->
  <div class="flex flex-col">
    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Name
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Email
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Start Date
              </th>
            </tr>
            </thead>
            <tbody>
            <!-- Odd row -->
            <% @employees.each do |employee| %>
              <tr class="bg-white">
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><%= employee.name %></td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= employee.email %></td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= employee.start_date.to_date %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

challenge/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "tailwind", media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "inter-font", media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <!-- This example requires Tailwind CSS v2.0+ -->
  <div>
    <div class="bg-gray-800 pb-32">
      <header class="py-10">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 class="text-3xl font-bold text-white">
            <%= controller_name.capitalize %>
          </h1>
        </div>
      </header>
    </div>

    <main class="-mt-32">
      <div class="max-w-7xl mx-auto pb-12 px-4 sm:px-6 lg:px-8">
        <!-- Replace with your content -->
        <div class="bg-white rounded-lg shadow px-5 py-6 sm:px-6">
          <%= yield %>
        </div>
        <!-- /End replace -->
      </div>
    </main>
  </div>
  </body>
</html>